export interface BlogPost {
  id: number;
  titleKey: string;
  descriptionKey: string;
  image: string;
  date: string;
  time: string;
  views: number;
}

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    titleKey: "blog.posts.completeCryptoGuide",
    descriptionKey: "blog.descriptions.completeCryptoGuideDesc",
    image: "/images/blog_1.png",
    date: "Dec 15, 2024",
    time: "10:30 AM",
    views: 1250,
  },
  {
    id: 2,
    titleKey: "blog.posts.bitcoinAnalysis2024",
    descriptionKey: "blog.descriptions.bitcoinAnalysis2024Desc",
    image: "/images/blog_1.png",
    date: "Dec 12, 2024",
    time: "2:15 PM",
    views: 890,
  },
  {
    id: 3,
    titleKey: "blog.posts.riskManagement",
    descriptionKey: "blog.descriptions.riskManagementDesc",
    image: "/images/blog_1.png",
    date: "Dec 10, 2024",
    time: "9:45 AM",
    views: 2100,
  },
  {
    id: 4,
    titleKey: "blog.posts.technicalAnalysis",
    descriptionKey: "blog.descriptions.technicalAnalysisDesc",
    image: "/images/blog_2.png",
    date: "Dec 8, 2024",
    time: "4:20 PM",
    views: 1680,
  },
  {
    id: 5,
    titleKey: "blog.posts.choosingExchange",
    descriptionKey: "blog.descriptions.choosingExchangeDesc",
    image: "/images/blog_2.png",
    date: "Dec 5, 2024",
    time: "11:10 AM",
    views: 950,
  },
  {
    id: 6,
    titleKey: "blog.posts.blockchainFuture",
    descriptionKey: "blog.descriptions.blockchainFutureDesc",
    image: "/images/blog_2.png",
    date: "Dec 3, 2024",
    time: "1:30 PM",
    views: 1420,
  },
  {
    id: 7,
    titleKey: "blog.posts.defiProtocols",
    descriptionKey: "blog.descriptions.defiProtocolsDesc",
    image: "/images/blog_2.png",
    date: "Dec 1, 2024",
    time: "3:45 PM",
    views: 1850,
  },
  {
    id: 8,
    titleKey: "blog.posts.nftTrends",
    descriptionKey: "blog.descriptions.nftTrendsDesc",
    image: "/images/blog_2.png",
    date: "Nov 28, 2024",
    time: "10:15 AM",
    views: 1320,
  },
  {
    id: 9,
    titleKey: "blog.posts.cryptoRegulations",
    descriptionKey: "blog.descriptions.cryptoRegulationsDesc",
    image: "/images/blog_2.png",
    date: "Nov 25, 2024",
    time: "2:30 PM",
    views: 980,
  },
  {
    id: 10,
    titleKey: "blog.posts.smartContractDev",
    descriptionKey: "blog.descriptions.smartContractDevDesc",
    image: "/images/blog_2.png",
    date: "Nov 22, 2024",
    time: "9:20 AM",
    views: 2250,
  },
  {
    id: 11,
    titleKey: "blog.posts.cryptoMining",
    descriptionKey: "blog.descriptions.cryptoMiningDesc",
    image: "/images/blog_2.png",
    date: "Nov 20, 2024",
    time: "4:10 PM",
    views: 1750,
  },
  {
    id: 12,
    titleKey: "blog.posts.portfolioDiversification",
    descriptionKey: "blog.descriptions.portfolioDiversificationDesc",
    image: "/images/blog_2.png",
    date: "Nov 18, 2024",
    time: "11:45 AM",
    views: 1450,
  },
  {
    id: 13,
    titleKey: "blog.posts.stakingPassiveIncome",
    descriptionKey: "blog.descriptions.stakingPassiveIncomeDesc",
    image: "/images/blog_2.png",
    date: "Nov 15, 2024",
    time: "1:20 PM",
    views: 1680,
  },
  {
    id: 14,
    titleKey: "blog.posts.layer2Solutions",
    descriptionKey: "blog.descriptions.layer2SolutionsDesc",
    image: "/images/blog_2.png",
    date: "Nov 12, 2024",
    time: "3:15 PM",
    views: 1290,
  },
  {
    id: 15,
    titleKey: "blog.posts.cryptoTax",
    descriptionKey: "blog.descriptions.cryptoTaxDesc",
    image: "/images/blog_2.png",
    date: "Nov 10, 2024",
    time: "10:50 AM",
    views: 1120,
  },
  {
    id: 16,
    titleKey: "blog.posts.securityBestPractices",
    descriptionKey: "blog.descriptions.securityBestPracticesDesc",
    image: "/images/blog_2.png",
    date: "Nov 8, 2024",
    time: "2:40 PM",
    views: 1950,
  },
  {
    id: 17,
    titleKey: "blog.posts.altcoinAnalysis",
    descriptionKey: "blog.descriptions.altcoinAnalysisDesc",
    image: "/images/blog_2.png",
    date: "Nov 5, 2024",
    time: "9:30 AM",
    views: 1380,
  },
  {
    id: 18,
    titleKey: "blog.posts.marketPsychology",
    descriptionKey: "blog.descriptions.marketPsychologyDesc",
    image: "/images/blog_2.png",
    date: "Nov 3, 2024",
    time: "4:25 PM",
    views: 1560,
  },
  {
    id: 19,
    titleKey: "blog.posts.institutionalAdoption",
    descriptionKey: "blog.descriptions.institutionalAdoptionDesc",
    image: "/images/blog_2.png",
    date: "Nov 1, 2024",
    time: "11:35 AM",
    views: 1720,
  },
  {
    id: 20,
    titleKey: "blog.posts.web3DApps",
    descriptionKey: "blog.descriptions.web3DAppsDesc",
    image: "/images/blog_2.png",
    date: "Oct 29, 2024",
    time: "1:55 PM",
    views: 1840,
  },
];
