name: Build & Deploy (Bluehost SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: "prod-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.capitalchain.co  # optional: shows link in Actions UI

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build   # you have output:'export' so this writes to /out

      - name: Add .htaccess to out
        run: |
          if [ -f "public/.htaccess" ]; then
            cp -f public/.htaccess out/.htaccess
          fi

      - name: Deploy to Bluehost via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            **/.DS_Store
            **/Thumbs.db
